# Generated by Django 4.1.4 on 2023-01-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_equipment', '0003_category_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Ваше имя')),
                ('date_burn', models.DateTimeField(blank=True, max_length=50, null=True, verbose_name='дата рождения')),
                ('telefon', models.IntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание')),
            ],
        ),
    ]
